disabled_rules:
  - trailing_whitespace
  - unused_optional_binding
  
excluded:
  - Carthage
  - Pods
  
line_length:
  warning: 140
  error: 280
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
    
identifier_name:
  min_length: 3
  max_length: 40
  allowed_symbols: "_"
  excluded:
    - id
    - URL
    - GlobalAPIKey
